### ISSUE TITLE
Documents should be tailing with .rst?

### ISSUE THREAD

**Issue by kxxoling** [avanov/Plim#43]
Cause they all are reST formatted files, tailing with `.rst` would be more absolute and can benefits more from text editor like Vim.

**Comment by avanov** [comment]
Can you make a pull request?

**Comment by kxxoling** [comment]
@avanov Sure, Chinese translation is also almost finished, but still needs technic review.

**Comment by kxxoling** [comment]
@avanov I need a new branch to carry on this fix, what would be a proper branch name?

**Comment by avanov** [comment]
@kxxoling it doesn't matter. Just derive it from the develop branch of the upstream repository (this one) and then create a PR into the same develop branch.

**Comment by kxxoling** [comment]
I created a branch named doctype-change from master branch cause my develop branch is changed and  not ready for merge, a PR would come from my doctype-change branch to your master, is that OK?

**Comment by avanov** [comment]
Not really, in that case I would have to merge it into my master, when all changes should go into the develop first. You can branch out from develop without losing your changes by using stash/unstash technique - http://git-scm.com/docs/git-stash

**Comment by avanov** [comment]
If you have already changed the develop branch of your remote repo, then you can start a new branch from the develop of upstream. Names of your branches do not matter so long they are started from the upstream's develop.

**Comment by avanov** [comment]
You may find the following links useful:
* https://help.github.com/articles/configuring-a-remote-for-a-fork/
* https://help.github.com/articles/fork-a-repo/
