### ISSUE TITLE
A case against the omission of Slim's /! syntax

### ISSUE THREAD

**Issue by MagnusOxlund** [avanov/Plim#50]
I've been reading the documentation in order to determine if Plim is the right tool for me. The decision to omit Slim's HTML comment syntax struck me as odd given the explanation: 

> There is no an[sic] equivalent syntax for Slim’s “/!” html comment. This line indicator has been considered redundant since Plim supports raw HTML tags.

(http://plim.readthedocs.io/en/latest/syntax.html#line-indicators)

Assuming redundancy as determined by support for regular HTML syntax is not the argument, but that it's instead implied that the advantage offered by Slim's /! syntax over the specific HTML comment tag is negligible, I just want to add that in the long term, typing `/! my comment` is noticeably less cumbersome than typing `<!-- my comment -->` .

**Comment by avanov** [comment]
Hi @MagnusOxlund,

I tend to agree with you now, even though, in a hindsight, there was a reason not to include it - I had a few projects that used the lib, and I wanted to restrict the available syntax to certain constructions. Namely, I wanted to keep comments in html, if there was a necessity to have comments in the first place. Hence the above decision.

If you prepare a PR for the slim-style comments, I'll happily review it.

**Comment by MagnusOxlund** [comment]
I had a look at the lexer module. I ended up deciding on a different preprocessor for my projects, so familiarizing myself sufficiently with the package in order to write the pull request looks like it would be too involved for the time being.

Should that change in favor of Plim sometime in the near future, I will be happy to dive in.
